---
abstract: 'FIRST and NEXT functions for loops'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Loop-Control
provides:
  Loop::Control:
    file: lib/Loop/Control.pm
    version: 1.100861
requires:
  Carp: 0
  English: 0
  Exporter: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Scope::Upper: 0
  Test::Differences: 0
  Test::More: 0.88
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Loop-Control
  homepage: http://search.cpan.org/dist/Loop-Control/
  repository: http://github.com/hanekomu/Loop-Control
version: 1.100861
