---
abstract: 'FIRST and NEXT functions for loops'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  Test::More: 0.70
distribution_type: module
generated_by: 'Module::Install version 0.80'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Loop-Control
no_index:
  directory:
    - inc
    - t
requires:
  Scope::Upper: 0
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Loop-Control
  homepage: http://search.cpan.org/dist/Loop-Control/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/hanekomu/loop-control/tree/master
version: 0.01
